import type { Metadata } from "next";
import {Intel_One_Mono } from "next/font/google";
import "./globals.css";

const intelOneMono = Intel_One_Mono({
  variable: "--font-intel-one-mono",
  subsets: ["latin"],
  weight: "400",
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${intelOneMono.variable} antialiased`}>{children}</body>
    </html>
  );
}
